# Generated by Django 4.2.5 on 2023-10-04 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gerente', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta_bancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('tipo_conta', models.CharField(choices=[('Poupança', 'Poupança'), ('Corrente', 'Corrente'), ('Salario', 'Salario')], max_length=8)),
                ('agencia', models.IntegerField()),
                ('saldo', models.FloatField()),
                ('limite_especial', models.FloatField()),
                ('gerente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_gerenciadas', to='gerente.gerente')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_bancarias', to='cliente.cliente')),
            ],
        ),
    ]
