# Generated by Django 4.2.5 on 2023-10-15 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerente', '0002_remove_gerente_id_alter_gerente_cpf'),
        ('conta', '0002_alter_conta_bancaria_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta_bancaria',
            name='gerente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_gerenciadas', to='gerente.gerente'),
        ),
    ]
