# Generated by Django 4.2.3 on 2023-10-15 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0003_alter_conta_bancaria_gerente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conta_bancaria',
            old_name='cliente',
            new_name='id_cliente',
        ),
    ]
