# Generated by Django 4.2.5 on 2023-10-26 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0005_rename_id_cliente_conta_bancaria_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('entrada', 'entrada'), ('saida', 'saida')], max_length=7)),
                ('valor', models.FloatField()),
                ('descricao', models.CharField(max_length=100)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacoes_origem', to='conta.conta_bancaria')),
            ],
        ),
    ]
