# Generated by Django 4.2.3 on 2023-10-24 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boleto', '0002_remove_boleto_id_alter_boleto_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='pago',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
