# Generated by Django 4.2.5 on 2023-10-18 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='id_produto',
            new_name='produto',
        ),
    ]
