# Generated by Django 4.2.5 on 2023-09-25 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_customuser_data_nascimento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
