# Generated by Django 4.2.5 on 2023-10-18 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_rename_id_produto_produto_produto'),
        ('concessao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concessao',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='produto.produto'),
        ),
    ]
