# Generated by Django 4.2.5 on 2023-10-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concessao', '0003_alter_concessao_data_primeiro_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concessao',
            name='data_primeiro_vencimento',
            field=models.DateField(),
        ),
    ]
